// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9yd0EsGqzQO3OqZxysJfOoeutUEnd7nw',
    appId: '1:283628360445:web:16cff5ff847b7723862494',
    messagingSenderId: '283628360445',
    projectId: 'scaut-dev',
    authDomain: 'scaut-dev.firebaseapp.com',
    storageBucket: 'scaut-dev.firebasestorage.app',
    measurementId: 'G-9YE31C0D57',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCHphQbGOExOBAHr0EenJGl2upg4DgII0',
    appId: '1:283628360445:android:73b0a0a6978542e5862494',
    messagingSenderId: '283628360445',
    projectId: 'scaut-dev',
    storageBucket: 'scaut-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsmjfHmikjVi8aCgwnOwgL4gMr3IFWuUw',
    appId: '1:283628360445:ios:0ae4c98d77b79fce862494',
    messagingSenderId: '283628360445',
    projectId: 'scaut-dev',
    storageBucket: 'scaut-dev.firebasestorage.app',
    iosBundleId: 'com.aicserrock.scaut',
  );
}
